# Generated by Django 5.2.2 on 2025-06-13 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(default='Uncategorized', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JournalistModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('image_select', models.ImageField(upload_to='images/')),
                ('description', models.TextField()),
                ('published_on', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='news_app.categorymodel')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Journalist', to='news_app.journalistmodel')),
            ],
        ),
    ]
