# Generated by Django 5.2.2 on 2025-06-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
