# Generated by Django 5.2.2 on 2025-06-16 11:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_remove_articlemodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='image_select',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
